debugging

diff --git a/.github/workflows/developing.yml b/.github/workflows/developing.yml
--- a/.github/workflows/developing.yml
+++ b/.github/workflows/developing.yml
@@ -47,34 +47,37 @@ jobs:
         env:
           # Remember, the mdn/content repo got cloned into `pwd` into a
           # sub-folder called "mdn/content"
-          CONTENT_ROOT: "${{ github.workspace }}/content/files"
+          CONTENT_ROOT: "${{ github.workspace }}/mdn/content/files"
         run: |
-          yarn prepare-build
-          yarn start > /tmp/stdout.log 2> /tmp/stderr.log &
+          echo $CONTENT_ROOT
+          ls -l
+          ls -l "$CONTENT_ROOT"
+      #     yarn prepare-build
+      #     yarn start > /tmp/stdout.log 2> /tmp/stderr.log &
 
-      - name: Wait for servers
-        run: |
-          # Just a slight delay to wait until the dev server is ready.
-          sleep 5
+      # - name: Wait for servers
+      #   run: |
+      #     # Just a slight delay to wait until the dev server is ready.
+      #     sleep 5
 
-          curl --retry-connrefused --retry 5 http://localhost:5000 > /dev/null
-          curl --retry-connrefused --retry 5 --silent http://localhost:3000 > /dev/null
+      #     curl --retry-connrefused --retry 5 http://localhost:5000 > /dev/null
+      #     curl --retry-connrefused --retry 5 --silent http://localhost:3000 > /dev/null
 
-      - name: Test viewing the dev server
-        env:
-          # This will make sure the tests in `testing/tests/*.test.js` only run
-          # if the development server is up and ready to be tested.
-          TESTING_DEVELOPING: true
-        run: |
-          status=0
-          yarn test:testing developing || (
-            status=$?
-            echo "Testing failed! Going to dump stdout and stderr"
-            echo "STDOUT..................................................."
-            cat /tmp/stdout.log
-            echo "STDERR..................................................."
-            cat /tmp/stderr.log
-            echo $status
-            exit $status
-          )
-          exit $status
+      # - name: Test viewing the dev server
+      #   env:
+      #     # This will make sure the tests in `testing/tests/*.test.js` only run
+      #     # if the development server is up and ready to be tested.
+      #     TESTING_DEVELOPING: true
+      #   run: |
+      #     status=0
+      #     yarn test:testing developing || (
+      #       status=$?
+      #       echo "Testing failed! Going to dump stdout and stderr"
+      #       echo "STDOUT..................................................."
+      #       cat /tmp/stdout.log
+      #       echo "STDERR..................................................."
+      #       cat /tmp/stderr.log
+      #       echo $status
+      #       exit $status
+      #     )
+      #     exit $status
